### ISSUE TITLE
'Generate!' button is not visible on 'Generate records' page.

### ISSUE THREAD

**Issue by guptas-sugarcrm** [sugarcrm/SidecarDevTools#24]
**SUMMARY**
'Generate!' button is not visible on 'Generate records' page.

**ENVIRONMENT**
- Sidecar Debugger Tool - 0.1
- Google Chrome - 45
- SugarCRM Enterprise, Version 7.7.0.0beta5 (Build 1737)

**STEPS TO REPRODUCE**
1. Login to Sugar as an admin user.
2. Navigates to Accounts module.
3. Open the 'SugarDebug' tab in the Chrome dev tool.
4. Go to 'Generate records' tab
5. Scroll down the page.

**EXPECTED RESULT**
5. 'Generate!' button should appear on 'Generate records' page.

**ACTUAL RESULT**
5. 'Generate!' button is not visible on 'Generate records' page.

**ATTACHED SCREENSHOT**

<img width="598" alt="generatebtn" src="https://cloud.githubusercontent.com/assets/9282163/9914695/b22fa028-5cd0-11e5-9e2a-0eab7884d84a.png">

**Comment by mmarum-sugarcrm** [comment]
Fixed now for me.  Please re-open if you still find this issue in lastest master branch.

**Comment by guptas-sugarcrm** [comment]
@mmarum-sugarcrm, Sorry for the delay. But I am still facing this issue.
For more clarity please have a look into the video http://recordit.co/Mu2g5LR32o
The 'Generate Page' should be fully scroll-able.

NOTE: "Generate !" button is visible only when we open the console window separately and again the button is not visible when er expend the size of any text field (i.e. 'Add your own attributes:' and 'Add options:' text field)

**Comment by yvan33** [comment]
@UTAlan - Thank you for your help!
Here is a new PR that apply the `scss` change into the `css` file using the watcher. The license header in `*.css` files have been updated too : #33 
@mmarum-sugarcrm can you take a quick look and let me know if the bug is fixed so I can merge it ?
Thanks

**Comment by yvan33** [comment]
merged PR #33: https://github.com/sugarcrm/SidecarDevTools/commit/5257f5bf360b2c5a2bbdf63fb7f478da1528b3fa
